config/routes.rb
Rails.application.routes.draw do

  get "/about" => "about#index", as: :about

  get "/contact" => "contact#index", as: :contact
  post "/contact" => "contact#create"
  get "/welcome/:name" => "welcome#show", as: :welcome

  root "welcome#index"

end

app/controllers/about_controller.rb
#all conteollers have the suffix: Controller
#they should inherit from clasees that eventually inherit from 
# ActionController: : Base
#most likely controllers will inherit from ApplicationController


class AboutController < ApplicationController

#this is a method deofined withon the AboutController
#this is called "Action"
#so the route : get"/about" => "about#index"
#will call this method
  def index
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
 #contriller use application.html.erb inside of views/layouts
 #as the default layout, unless you specify something like:
 #layout "special"
 #then this will use views/layout/apecial.html.erb
 #for all the actions inside this contriller 


  def index
  #this will render views/contacts/index.html.erb
  #within layout: views/layout/application.html.erb
  #unless you specify somthing like:


  end
 def create
 	@name = params[:full_name]
 	@email = params[:email]
 	@message = params[:message]
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	

	def index
	
	end
	
	def show
      @name = params[:name]
	end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/contact/create.html.erb
<h1>Thanks you for contacting us</h1>

<p>name: <%= @name %></p>
<p>email: <%= @email %></p>
<p>message: <%= @message %></p>

app/views/contact/index.html.erb
<h1>contacts Us</h1>

<%= form_tag "/contact" do %>
  
  <%= text_field_tag :full_name, "", placeholder: "Full Name" %>
  <br>

  <%= email_field_tag :email, "" ,placeholder: "Email" %> 
  <br>
  <%= text_area_tag :message, "" ,placeholder: "Your Message" %> 
  <br>
  <%= submit_tag :submit %>

	<% end %>

app/views/contact/index.xml.erb
<?xml version="1.0"?>
<home>
 <message>Contact Us</message>
 </home>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", root_path %>
|
<%= link_to "About", about_path %>
|
<%= link_to "Contact", contact_url %>
<hr>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

app/views/welcome/show.html.erb
<h1>Hello <%= @name %></h1>